"""
Export YouTube cookies for Render deployment

This script exports YouTube cookies from your browser and encodes them
in base64 format for use as an environment variable on Render.

Requirements:
    pip install browser-cookie3

Usage:
    python export_youtube_cookies.py
    
Output:
    - Creates youtube_cookies.txt (raw Netscape format)
    - Creates youtube_cookies_b64.txt (base64 encoded for Render)
    - Prints instructions for adding to Render
"""

import sys

try:
    import browser_cookie3
except ImportError:
    print("❌ browser-cookie3 not installed!")
    print("\nInstall it with:")
    print("  pip install browser-cookie3")
    sys.exit(1)

import base64
from pathlib import Path

print("=" * 70)
print("🍪 YouTube Cookie Exporter for Render")
print("=" * 70)

# Try to extract cookies from Chrome
print("\n📂 Extracting cookies from Chrome...")
try:
    cookies = list(browser_cookie3.chrome(domain_name='youtube.com'))
    
    if not cookies:
        print("⚠️  No YouTube cookies found in Chrome")
        print("\nMake sure you:")
        print("  1. Have Chrome installed")
        print("  2. Are logged into YouTube in Chrome")
        print("  3. Have visited youtube.com recently")
        sys.exit(1)
    
    print(f"✅ Found {len(cookies)} YouTube cookies")
    
except Exception as e:
    print(f"❌ Failed to extract cookies: {e}")
    print("\nAlternative method:")
    print("  1. Install Chrome extension: 'Get cookies.txt LOCALLY'")
    print("  2. Visit YouTube")
    print("  3. Click extension → Export")
    print("  4. Save as youtube_cookies.txt")
    sys.exit(1)

# Write cookies in Netscape format
cookie_file = Path('youtube_cookies.txt')
print(f"\n💾 Writing cookies to {cookie_file}...")

with open(cookie_file, 'w') as f:
    f.write('# Netscape HTTP Cookie File\n')
    f.write('# This file was generated by export_youtube_cookies.py\n\n')
    
    for cookie in cookies:
        # Netscape format: domain flag path secure expiration name value
        f.write(f'{cookie.domain}\t')
        f.write(f'TRUE\t')
        f.write(f'{cookie.path}\t')
        f.write(f'{"TRUE" if cookie.secure else "FALSE"}\t')
        f.write(f'{cookie.expires if cookie.expires else 0}\t')
        f.write(f'{cookie.name}\t')
        f.write(f'{cookie.value}\n')

print(f"✅ Saved {cookie_file}")

# Encode in base64 for Render
print("\n🔒 Encoding cookies in base64...")
with open(cookie_file, 'rb') as f:
    cookie_data = f.read()
    cookie_b64 = base64.b64encode(cookie_data).decode('utf-8')

b64_file = Path('youtube_cookies_b64.txt')
with open(b64_file, 'w') as f:
    f.write(cookie_b64)

print(f"✅ Saved {b64_file}")

# Print instructions
print("\n" + "=" * 70)
print("🎉 SUCCESS! Cookies exported")
print("=" * 70)
print("\n📋 NEXT STEPS - Add to Render:")
print("\n1. Go to Render Dashboard → Your Service → Environment")
print("2. Add New Environment Variable:")
print("   Key:   YOUTUBE_COOKIES_B64")
print(f"   Value: (paste content from {b64_file})")
print("\n3. Click 'Save' to trigger redeploy")
print("\n4. Test YouTube download - it should now work!")
print("\n" + "=" * 70)
print("\n⚠️  SECURITY NOTE:")
print("  - Keep youtube_cookies*.txt files PRIVATE")
print("  - Add to .gitignore (already done)")
print("  - Cookies expire after ~6 months")
print("  - Re-export when expired")
print("\n" + "=" * 70)

# Show first 100 chars of base64 for verification
print(f"\n🔍 Base64 preview (first 100 chars):")
print(cookie_b64[:100] + "...")
print(f"\n📏 Total length: {len(cookie_b64)} characters")
